# Generated by Django 3.0.6 on 2020-06-16 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='tasks',
        ),
    ]
